### ISSUE TITLE
Подумать об уникальных именах контейнеров для разных микросервисов

### ISSUE THREAD

**Issue by Bacher** [GolosChain/gate-service#21]
@Bacher commented on [Wed Dec 19 2018](https://github.com/GolosChain/tolstoy/issues/1831)

Подумать об уникальных именах контейнеров для разных микросервисов.

Это решит неудобство при локальной разработке.

**Comment by Format-X22** [comment]
Подумали и решили что будут, но по факту модификаций каждого из них.
