### ISSUE TITLE
В результатах content.getProfile не обновляются поля subscriptions для комьюнити

### ISSUE THREAD

**Issue by Bacher** [GolosChain/gate-service#44]
После того как пользователь запинил сообщество (pin), в выдаче content.getProfile не появляется это сообщество в списке `subscriptions.communities`

```javascript
"subscriptions": {
    "userIds": [],
    "communities": []
},
"stats": {
    "postsCount": 0
},
"userId": "funny.man",
"username": "funny.man",
"registration": {
    "time": "2019-03-18T07:26:51.000Z"
}
```

**Comment by Format-X22** [comment]
Сообщества не пинятся т.к. не реализована необходимая функциональность на блокчейне, по мере появления - пин появится. Но отдельного тикета на пины не было, оставлю.
